server:
  port: 9876

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  cloud:
    discovery:
      enabled: true
  application:
    name: author-service
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_ADVERTISED_LISTENERS}
      group-id: authorGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: ru.fedbon.voteservice.producer.VoteAuthorMessage:ru.fedbon.authorservice.consumer.VoteAuthorMessage

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.fedbon.authorservice.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI}

logging:
  level:
    root: INFO